### ISSUE TITLE
not centered on first hover

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/paper-tooltip#5]
Not centered on first hover when page has been refreshed. 
On second hover and the following it is.

**Comment by notwaldorf** [comment]
@gertcuykens Do you have a jsbin with a repro case? This looks fine for me locally...:(

**Comment by gertcuykens** [comment]
I was afraid for this haha :) Ok going to dig around and try to make a example

**Comment by gertcuykens** [comment]
@notwaldorf imports and jsbin is not making me happy... anyway here is my app http://g-11.appspot.com top right corner

![image](https://cloud.githubusercontent.com/assets/863731/8682447/4fdb5d3a-2a6d-11e5-95e9-8a8c6ac60920.png)

![image](https://cloud.githubusercontent.com/assets/863731/8682452/59de8974-2a6d-11e5-8af4-210a493c6c5b.png)

**Comment by notwaldorf** [comment]
@gertcuykens cool thanks! taking a look.

**Comment by gertcuykens** [comment]
@notwaldorf Maybe while your add click on 

![image](https://cloud.githubusercontent.com/assets/863731/8686675/9c02fa04-2a88-11e5-8aae-dc099a445c93.png)

and why the iron list is not flexing I have reported it on iron list + slack but no response yet. If it is a bug please make issue on iron-list because i am not technical enough to explain what is going on.

**Comment by notwaldorf** [comment]
cc @blasten for iron-list issue above :)

**Comment by blasten** [comment]
@gertcuykens  I tried using `flex` and there's an issue that has nothing to do with the class `flex`, but rather the fact that iron-list creates a fixed number of DOM items  (20 to be more specific). I have sent a PR that will automatically determinate how many DOM items should be rendered based on the item's height and the viewport height. https://github.com/PolymerElements/iron-list/tree/check-customelements that should fix the issue you have. :)

**Comment by notwaldorf** [comment]
@gertcuykens Would you mind giving it a try with the latest release I just tagged? Thanks

**Comment by gertcuykens** [comment]
http://gcl-12.appspot.com/

paper-tooltip#1.0.1 bower_components/paper-tooltip
├── neon-animation#1.0.6
├── paper-styles#1.0.11
└── polymer#1.0.8

Doesn't work for me or do I still have the old one?

**Comment by notwaldorf** [comment]
The app seems to have changed, so I can no longer repro this
